[package]
name = "feuer-types"
description = "Shared immutable-object range contract types for Feuer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
exclude.workspace = true

[dependencies]
bytes = { workspace = true }
bytesize = "2.7"
fnv = "1"
thiserror = { workspace = true }
xxhash-rust = { version = "0.8", features = ["xxh3"] }

[lints]
workspace = true
