[package]
name = "feuer-types"
description = "Shared immutable-object range contract types for Feuer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
exclude.workspace = true

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
