[package]
name = "feuer-historian"
description = "Request history and decayed access counts for immutable objects and byte ranges"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
exclude.workspace = true

[dependencies]
feuer-types = { workspace = true }
rustc-hash = { workspace = true }

[lints]
workspace = true
