[package]
name = "feuer-memory"
description = "Internal range memory tier with a soft allocation-byte target for Feuer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
exclude.workspace = true

[features]
benchmark = []

[dependencies]
bytes = { workspace = true }
bytesize = "2.7"
feuer-types = { workspace = true }
mixtrics = { workspace = true }
parking_lot = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]
mixtrics = { workspace = true, features = ["prometheus"] }
prometheus = { workspace = true }

[lints]
workspace = true
